# Generated by Django 4.1.4 on 2023-03-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.DecimalField(blank=False, decimal_places=0, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
