# Generated by Django 4.1.4 on 2023-03-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_age_person_district_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
    ]
