# Generated by Django 4.1.4 on 2023-03-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='gen_ins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('food_items', models.TextField()),
                ('mal_ins', models.TextField()),
                ('age', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, null=True)),
                ('in_1', models.CharField(max_length=15, null=True)),
                ('in_2', models.CharField(max_length=15, null=True)),
                ('in_3', models.CharField(max_length=15, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='cover/')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
