# Generated by Django 3.2.12 on 2023-03-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ins',
            field=models.TextField(null=True),
        ),
    ]
