# Generated by Django 4.1.4 on 2023-05-19 11:49

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_recipe_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen_ins',
            name='food_items',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='gen_ins',
            name='instructions',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='gen_ins',
            name='mal_ins',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ins',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
