# Generated by Django 4.1.4 on 2023-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_gen_ins_food_items_alter_gen_ins_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen_ins',
            name='food_items',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gen_ins',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gen_ins',
            name='mal_ins',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ins',
            field=models.TextField(null=True),
        ),
    ]
