# Generated by Django 4.1.4 on 2023-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_gen_ins_food_items_alter_gen_ins_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mother_ins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('food_items', models.TextField()),
                ('mal_ins', models.TextField()),
                ('age', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mother_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, null=True)),
                ('in_1', models.CharField(max_length=15, null=True)),
                ('in_2', models.CharField(max_length=15, null=True)),
                ('in_3', models.CharField(max_length=15, null=True)),
                ('ins', models.TextField(null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
