# Generated by Django 4.1.4 on 2023-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mother_ins_mother_recipe_recipe_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='in_1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='in_2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='in_3',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ing',
            field=models.TextField(null=True),
        ),
    ]
