# Generated by Django 4.1.4 on 2023-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_recipe_in_1_remove_recipe_in_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='people_served',
            field=models.TextField(null=True),
        ),
    ]
