# Generated by Django 4.1.4 on 2023-05-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recipe_calories_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother_recipe',
            name='in_1',
        ),
        migrations.RemoveField(
            model_name='mother_recipe',
            name='in_2',
        ),
        migrations.RemoveField(
            model_name='mother_recipe',
            name='in_3',
        ),
        migrations.AddField(
            model_name='mother_recipe',
            name='calories',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mother_recipe',
            name='difficulty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mother_recipe',
            name='ing',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mother_recipe',
            name='people_served',
            field=models.TextField(null=True),
        ),
    ]
